package.json

please check and update other dependency if required.

upgrade ts node

---

package.json

update to latest universal zones and rimraf

chore(package.json): Update dependencies

---

src/app/app.component.ts
src/index.html
src/server.ts

Updated general app styles.
Obviously can spend more time & change/tweak anything you guys would like, just let me know!
@jeffwhelpley @gdi2290

style(app): Update app styles

---

README.md
src/server.ts

docs(readme,server.ts): describe Promise polyfills compatibility

---

src/app.browser.module.ts
src/app.node.module.ts
src/app/app.component.ts
src/app/app.routes.ts
src/app/home.component.ts

https://github.com/angular/universal-starter/issues/205

refactor: share same routes

---

src/app/app.browser.module.ts
src/app/app.node.module.ts
src/client.ts
src/server.ts

https://github.com/angular/universal-starter/issues/209

refactor: move app.node.module.ts and app.browser.module.ts to app/

---

README.md

docs(readme): add universal gotchas & upcoming features

---

src/app/about/about-routing.module.ts
src/app/about/about.module.ts
src/app/app-routing.module.ts
src/app/app.browser.module.ts
src/app/app.node.module.ts
src/app/home/home-routing.module.ts
src/app/home/home.module.ts
src/app/shared/shared.module.ts

fix https://github.com/angular/universal-starter/issues/220

feat: add SharedModule

---

README.md

docs(readme): update httpcacheservice link

---

src/server.aot.ts
src/server.routes.ts
src/server.ts

Added server.routes to reduce redundancies

Added server.routes

---

src/+app/+todo/todo.component.css
src/+app/+todo/todo.component.html
src/+app/+todo/todo.component.ts
src/+app/+todo/todo.schema.ts

Get todos via **API** by **ModelService** and push it in to the table.

todos in table

---

README.md
cli/README.md

Thanks @lazarljubenovic for pointing this out

fix(readme): typos

---

cli/README.md

docs(readme): update cli docs

---

cli/webpack.server.config.js

Fixes up issue: https://github.com/angular/angular/issues/11580

chore(webpack): add plugins to fix circular dependency warning

---

cli/server.ts
cli/webpack.server.config.js

fix(style): update server.ts

---

package.json
prerender.ts
server.ts
src/app/app.component.ts
src/app/app.module.ts
src/app/home/home.component.ts
src/app/lazy/lazy.module.ts
src/main.server.ts
src/main.ts
tslint.json

* Add linting with parity to defaults provided by Angular CLI
* Refactor existing code to conform with linting

feat(lint): add linting to universal starter

---

server.ts

1. `const  template` is unused
2. reorder imports

refactor: remove unused template

---

angular.json
package.json

add in production config for server bundle

---

package.json
yarn.lock

Ref here https://github.com/angular/universal-starter/issues/583

remove top level webpack dependancy

---

webpack.server.config.js

Since this runs on server, there is no need to minify the code

feat: disable `optimization` in server bundle

---

webpack.server.config.js

style: fix comment as it stats the opposite

---

package.json
yarn.lock

build: update dependencies

---

package.json
prerender.ts
server.tsconfig.json

Credit to @r-LaForge for pointing this out

build: remove webpack from prerender task
