angular/universal-starter

- package.json
Fixing the `zone.js` dep to be locked to `0.5.10` to fix `npm install` errors.
> chore(package): peer deps fix

- .gitignore
- Gruntfile.ts
- gulpfile.ts
- package.json
- src/app/app.ts
- src/client.ts
- src/index.html
- src/server-only-app/server-only-app.ts
- tsconfig.json
- typings.json
- webpack.config.js
Package versions updated.
Most of the app runs but server-only-app doesn't seem to work.
Also, prerender is showing an error on 'npm start' with the latest versions of gulp and grunt prerender packages. This was not occurring on the older versions.
TypeScript 1.8 is causing an error due to duplicate engineOptions interface so typescript is left at version 1.7.5 for now.
> chore(prerender): update package versions for prerender build

- typings.json
Body-parser added to registry now, previous github link was no longer working causing "Cannot find module: body-parser"
Linked to issue https://github.com/angular/universal/issues/349.
Should this be updated in the Universal project as well? Couldn't find where.
> Update body-parser typings

- Procfile
- README.md
- app.json
- src/server.ts
Not sure if this is useful, but as I noted a `Procfile` in the repository I figured it's not completely out of scope. This makes some modifications to allow for one-click deployment to Heroku including a deploy button. Based on the conversations in #122
This process is good for a starter application and quick trial/error tests from a developer that is new to Universal. As that is the focus of this repository, it seems appropriate. It's not necessarily a configuration recommended for production if hosting on Heroku. However, it's probably a bit out of scope of this demo to go deeper into recommended build processes and deployment configuration.
> chore(build): improve deployment to Heroku

- package.json
```
preLoaders: [
{ test: /\.js$/, loader: 'source-map-loader' }
],
```
has been removed from webpack.config.js because of this [PR](https://github.com/angular/universal-starter/commit/a40f0d1b24d04a62a72bd1199ad0334405a76534).
**source-map-loader** is not necessary now.
> remove source-map-loader

- package.json
- webpack.config.ts
`npm run build:prod` and gzip together, reduce to 310KB in production
> feat: add gzip

- webpack.config.ts
Added comma to weback.config.ts to prevent ts syntax error that comes after removing comments while enabling gzip compression. 
I faced the same error so thought will be good to add the comma to webpack config plugins array.
> added comma to weback.config to prevent ts syntax error 

- webpack.config.ts
It had some repeated modules. Furthermore, since last beta, angular material had a
reestructuring/renaming, so now everything is unified on
@angular/material
> Fix angular material dependency on webpack

- src/app/app.browser.module.ts
- src/app/app.node.module.ts
- src/app/shared/shared.module.ts
using forRoot prevents that more than one instance of the service will be created.
> Add forRoot to shared module

- src/index.html
It is strongly advised to declare document charset before content, especially title.
> set charset before any content

- webpack.prod.config.ts
Set value by value because an object overrides all other env variables.
This fixes bug #291
> fix(webpack.prod): ensure only 'NODE_ENV' and 'AOT' is defined in 'process.env'

- README.md
Updated to fix link:
- Use a [UniversalCache](https://github.com/angular/universal-starter/blob/master/src/%2Bapp/shared/model/model.service.ts#L34-L50) instead of regular Http, to save certain requests so they aren't re-ran again on the Client. ([Example useage here](https://github.com/angular/universal-starter/blob/cc71e2d5b2d783f2bb52eebd1b5c6fa0ba23f08a/src/%2Bapp/%2Bhome/home.component.ts#L22-L24))
> docs(readme): fix universalcache gotcha link

- README.md
There's a bug for current documentation when you use brotli as default compression.
Step to reproduce this issue. 
1. Visit http://localhost:8000/data.json on browser
2. Visit http://localhost:8000/home
Server will crash because of the following reasons,
The first time you visit data.json. Since browser accept br compression, it will compress data.json and save it to cache.
The second time you visit home, there is a server side rending but angular universal don't anticipate any encoding compression then a crash will happen.
Javascript is asynchronous function, so send function will be execute twice even callback function was execute before. We need `return` after send function.
> Bug: fix encoding bug when using brotli compression

- package.json
Just use webpack 3.3.0 until issue is resolved.
> fix(deps): latest webpack enhanched resolver breaks the AOT build

- cli/package.json
The [`reflect-metadata`](https://www.npmjs.com/package/reflect-metadata) module is used in both [server.js](https://github.com/angular/universal-starter/blob/master/cli/server.js#L2) and [predender.js](https://github.com/angular/universal-starter/blob/master/cli/prerender.js#L3), but it was forgotten in `package.json`.
> fix(cli/package.json): add reflect-metadata

- cli/prerender.ts
Right now, the prerender generates each page concurrently, which will cause an OOM error when there are a lot of pages. This change prerenders pages one at a time.
> Make prerender run in series

- cli/package.json
- cli/prerender.ts
- cli/src/tsconfig.app.json
- cli/src/tsconfig.server.json
- cli/static.paths.ts
* removed unnecessary logic in prerender.ts
* moved server.ts, prerender.ts and static.paths.ts into src since they are src files
* replaced static.paths.js with static.path.ts to be consistant
* changed platform-server version to match other versions
> refactor(cli): move ts files into src and clean up prerender

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/app.server.module.ts
* Adds TransferHttpCacheModule from nguniversal/common to avoid
duplicate HTTP calls between server and browser
* Bump RxJS dep to 5.5.5 to avoid issues with lower patch versions
* Clean up certain areas of code, remove redundant imports
PR close #509
> feat(http): add transfer cache module from nguniversal/common

- .angular-cli.json
lint config in .angular-cli.json is referencing tsconfig files which doesn't exist in the project
After having sync my app with the last changes of the repo, I wasn't able to commit anymore because lint was throwing error like
Commit failed with error
typeof-compare is deprecated. Starting from TypeScript 2.2 the compiler includes this check which makes this rule redundant.
error TS5058: The specified path does not exist: 'e2e/tsconfig.e2e.json'.
FatalError: error TS5058: The specified path does not exist: 'e2e/tsconfig.e2e.json'.
or
error TS5058: The specified path does not exist: 'src/tsconfig.spec.json'.
FatalError: error TS5058: The specified path does not exist: 'src/tsconfig.spec.json'.
Removing these two not existing references in .angular-cli.json solve the issue for me
> Fix lint and not existing tsconfig files

- webpack.server.config.js
The `main` part of the regex is redundant as because of the `.js` extension it is not matching the `require` statement in `server.ts`. If it was matching, so the `require` statement in `server.ts` had the `.js` ending , the generated bundle would fail as the output would look like this:
```js
/***/ }),
/* 257 */
/***/ (function(module, exports) {
module.exports = ./dist/server/main.bundle.js;
/***/ })
/******/ ]);
```
> chore(webpack): remove redundant `main` external regex

- webpack.server.config.js
This config disables the warning from webpack:
>System.import() is deprecated and will be removed soon. Use import() instead.
closes https://github.com/angular/universal-starter/issues/579
> disabled webpack System.import warning

- prerender.ts
Missing whitespaces
Tested with https://www.codefactor.io/
> lint(prerender.ts):  Forbidden 'var' keyword, use 'const' instead

- webpack.server.config.js
Avoid warnings given by codefactor.io and other linters by refactoring
the regex using capturing groups like in the lines below.
Linked to #579
> fix(webpack.server.config): Unnecessary escape character: \/

- package.json
Webpack cli is only required in a dev env
> build: move webpack-cli to a devDependency

- webpack.server.config.js
Following a convo with Fabian Wiles @Toxicable 09:10
@alan-agius4 we're actually planning on removing the webpack config from that when I get some time next But it should include all of node_modules I'm not sure when that exclude got there
Also, this doesn't have any effect in `Webpack 4` as the externals need to match the package name and not the path
> fix: remove exclude node_modules

- src/environments/environment.ts
Point to correct file. angular-cli.json does not exist anymore.
> Point to correct file. angular-cli.json does not exist anymore.

- angular.json
`ng new` generates this as a schema path.
As the workspace schema doesn't validate all properties within the builders
> fix: update angular cli schema path

- server.ts
At the moment, there is no clear explaination how to make an app-shell work togather with SSR and lazy loading.
See for more context https://github.com/angular/angular-cli/issues/9202
> fix: add addition section to make appshell work with lazyloading and ssr

- package.json
This fixes an issue I ran into while proving out a production-ready environment for hosting a Universal app. I noticed some *devDependencies* modules are required to be installed in order to run the application, which should not be the case.
Changes in a nutshell: Moves **express** and **reflect-metadata** from devDependencies to run dependencies.
1. Clone repo, run `npm install`
1. Build project with `npm run build:ssr`
1. Remove `node_modules`
1. Run `npm install --production` to install run-time modules
1. Run `node  dist/server`
Following these steps, the node server will crash on launch due to missing dependencies:
```internal/modules/cjs/loader.js:583
> node dist/server
throw err;
^
Error: Cannot find module 'reflect-metadata'
at Function.Module._resolveFilename …
```
> build: Move reflect-metadata & express from devDependencies to dependencies

- server.ts
Enabling this won't make lazy loading work.
See https://github.com/angular/angular-cli/issues/12921#issuecomment-446485664
> style: remove note for lazy loading
